spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    baseline-version: 0

  security:
    user:
      name: ENC(PzxhyS2jnzUTGLFlLktsr39y0i0k1k5v)
      password: ENC(YZyVBZaMn2WHAh75ZmSEeFqnaXGidmGl)


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
#      show-components: always
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  level:
    org:
      springframework:
        transaction: trace
        security: trace
      hibernate:
        orm.jdbc.bind: trace
        SQL: debug
#        type: trace
#        stat: debug
